### PR TITLE
add libgdal-kea as a dependency

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Now that `kea` is built as a plugin in conda-forge, add `libgdal-kea` as a dependency so a user gets the KEA driver which is kind of necessary for `pyshepseg`...

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Review by neilflood — APPROVED** [review]
Very good, thank you.

**Comment by gillins** [comment]
Superseded by #4

**Pull request closed without merging**
